# Generated by Django 3.0.11 on 2021-01-12 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20210112_0107'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
