# Generated by Django 3.0.11 on 2021-01-27 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_banner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='banner_img',
            new_name='image',
        ),
    ]
