# Generated by Django 3.0.11 on 2021-02-20 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20210203_1045'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
