# Generated by Django 3.1.7 on 2021-02-24 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shopee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=50)),
                ('categories', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=50)),
                ('img_urls_0', models.CharField(blank=True, max_length=50)),
                ('img_urls_1', models.CharField(blank=True, max_length=50)),
                ('img_urls_2', models.CharField(blank=True, max_length=50)),
                ('img_urls_3', models.CharField(blank=True, max_length=50)),
                ('img_urls_4', models.CharField(blank=True, max_length=50)),
                ('price', models.CharField(blank=True, max_length=50)),
                ('product_url', models.CharField(blank=True, max_length=50)),
                ('supplier', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
