# Generated by Django 3.0.11 on 2021-02-19 19:41

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_remove_comment_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='reply',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='product.Comment'),
        ),
    ]
