# Generated by Django 3.1.7 on 2021-03-19 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_auto_20210307_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.RemoveField(
            model_name='variants',
            name='color',
        ),
        migrations.RemoveField(
            model_name='variants',
            name='image_id',
        ),
        migrations.RemoveField(
            model_name='variants',
            name='price',
        ),
        migrations.RemoveField(
            model_name='variants',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='variants',
            name='size',
        ),
        migrations.AddField(
            model_name='images',
            name='img_url',
            field=models.URLField(default='https://foo.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='img_url',
            field=models.URLField(default='https://foo.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='src_url',
            field=models.URLField(default='https://foo.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productfromshopee',
            name='price_not_sale',
            field=models.TextField(default='123', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productfromshopee',
            name='variant_type',
            field=models.TextField(default='str'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='variant',
            field=models.TextField(default='None'),
        ),
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
