# Generated by Django 3.0.11 on 2021-01-10 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_customer_order_orderitem_product_shippinginfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingInfo',
        ),
    ]
