# Generated by Django 3.0.11 on 2021-01-10 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_customer_order_orderitem_product_shippinginfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='shippinginfo',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='shippinginfo',
            name='order',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ShippingInfo',
        ),
    ]
