# Generated by Django 3.0.11 on 2021-01-27 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_banner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
