# Generated by Django 3.1.4 on 2021-02-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_account_salt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='salt',
            field=models.CharField(max_length=1000),
        ),
    ]
