# Generated by Django 3.1.7 on 2021-03-19 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=5000)),
                ('last_name', models.CharField(max_length=5000)),
                ('address', models.CharField(max_length=5000)),
                ('city', models.CharField(max_length=5000)),
                ('district', models.CharField(max_length=5000)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=5000)),
                ('note', models.CharField(blank=True, max_length=10000)),
                ('address_op', models.CharField(blank=True, max_length=5000)),
                ('company', models.CharField(blank=True, max_length=5000)),
            ],
        ),
        migrations.AlterField(
            model_name='token',
            name='userID',
            field=models.IntegerField(),
        ),
    ]
